### PR TITLE
Setup CI/CD Pipeline

### PR DESCRIPTION
**Pull request by anjastrunk**

### CODE REVIEW

**Comment by berendt** [comment]
Is it possible to use the SCS Zuul instance?  I think that would be the preferred way.

**Comment by anjastrunk** [comment]
> Is it possible to use the SCS Zuul instance? I think that would be the preferred way.

I just want to trigger unit test execution for every PR. Should this be done in Zuul? IMO, GitHub Actions fit better...

**Comment by berendt** [comment]
As I understand it, Zuul should be used for everything in the future. I just wanted to point out, Github Actions is fine for me too.

**Comment by anjastrunk** [comment]
merged init #69.

**Pull request closed without merging**
